// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUTaeK-pj10P88s6Xt1-5_02k2ymMphcc',
    appId: '1:438190664201:web:5006d3ac07acdf87e9e6d8',
    messagingSenderId: '438190664201',
    projectId: 'empirical-axon-356811',
    authDomain: 'empirical-axon-356811.firebaseapp.com',
    storageBucket: 'empirical-axon-356811.appspot.com',
    measurementId: 'G-W63DJX3NWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6_IFk_1BkeqAF6pBQGiTHeedAjq61BM',
    appId: '1:438190664201:android:2f636714855f6a5ce9e6d8',
    messagingSenderId: '438190664201',
    projectId: 'empirical-axon-356811',
    storageBucket: 'empirical-axon-356811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx_1L4l04JLd_eATga-iiUt5uoDHqEhnA',
    appId: '1:438190664201:ios:4b5a5b85e5c6eaa7e9e6d8',
    messagingSenderId: '438190664201',
    projectId: 'empirical-axon-356811',
    storageBucket: 'empirical-axon-356811.appspot.com',
    iosClientId: '438190664201-bd262ljjv8m47niv0joliju0houq4afp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todpapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx_1L4l04JLd_eATga-iiUt5uoDHqEhnA',
    appId: '1:438190664201:ios:4b5a5b85e5c6eaa7e9e6d8',
    messagingSenderId: '438190664201',
    projectId: 'empirical-axon-356811',
    storageBucket: 'empirical-axon-356811.appspot.com',
    iosClientId: '438190664201-bd262ljjv8m47niv0joliju0houq4afp.apps.googleusercontent.com',
    iosBundleId: 'com.example.todpapp',
  );
}
